### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by nickz-t3** [MinusGix/lapce-copilot#8]
Thanks for the product! I'd love to use this. But I don't see it among the available plugins in lapce. Is there a way I can use it?

**Comment by MinusGix** [comment]
The plugin isn't in the available plugins for Lapce as the current stable release does not have the code that the extension requires for inline completions (we've been slow on making new stable releases).  
The nightly version of Lapce does support that, so if you use nightly then you can use the plugin.  
*However* since it isn't in the plugin store (no nightly-specific plugins yet :( ) you'll have to build this plugin manually, and then put it in your plugins folder.   
Which you can find In Lapce with 'Open Plugins Directory' in the top command palette. Note that nightly/stable use different folders, you'll want to put it in the nightly versions plugin folder.

**Comment by MinusGix** [comment]
After a little bit of thought I think I'll just update the copilot dist and then just put it on the plugins site with a warning about it requiring nightly.

**Comment by NikZak** [comment]
Thank you, this is very helpful

**Comment by MinusGix** [comment]
Okay, I've published the extension as "Copilot (Unofficial)". Took a bit because I needed to rework how it downloads the copilot dist files, but should work on nightly now.
